/**
 * @author PROFESORES DE IP
 * 
 *	EL PROGRAMA ALMACENARÁ 24 TEMPERATURAS (UNA POR CADA HORA DEL DÍA) EN UN VECTOR.
 *		UTILIZARÁ MÉTODOS SET Y GET PARA INTRODUCIR Y DEVOLVER LAS TEMPERATURAS.
 *		CALCULARÁ CON UN MÉTODO MEDIA() LA TEMPERATURA MEDIA.
 *		CALCULARÁ CON UN MÉTODO MAX() LA TEMPERATURA MÁXIMA.
 *
 *	FUNCIONES:
 *		TIPO [] NOMBRE = NEW TIPO [INT LONGITUD]		-		CREAR VECTOR
 *		NOMBRE [INT]		-		DEVOLVER VALOR EN POSICIÓN INT
 *		NOMBRE [INT] = VALOR		-		ALMACENAR VALOR EN POSICIÓN INT DE VECTOR
 *		NOMBRE.LENGTH		-		DEVOLVER LONGITUD DE VECTOR
 */

public class Temperatura {		//CLASE TEMPERATURAS
	//CREAREMOS LOS MÉTODOS PARA TRABAJAR CON LOS VECTORES
	
	/** VECTOR PRIVADO GRADOS*/
	private double[] grados = new double [24];		//NUEVO VECTOR QUE CONTIENE 24 DOUBLES LLAMADO GRADOS
			//TIPO	NOMBRE		  TIPO	 CANTIDAD
	
	/**
	 * MÉTODO SETGRADOS()
	 * @param hora - EQUIVALENTE A LA POSICIÓN DEL VALOR A INTRODUCIR EN EL VECTOR.
	 * @param temperatura - EQUIVALENTE A LA TEMPERATURA QUE SE INTRODUCIRÁ EN LA POSICIÓN HORA.
	 */
	public void setGrados (int hora,double temperatura) {		//AÑADE VALOR AL VECTOR
		if (hora>=0 && hora<=23);		//MIENTRAS QUE HAYA MENOS DE 24 VALORES (UNA PARA CADA HORA DEL DÍA)
			grados[hora] = temperatura;		//AÑADIR TEMPERATURA AL FINAL DEL VECTOR
		//(VECTOR[INT] = VALOR - ALMACENARÁ EL VALOR EN LA POSICIÓN INT DEL VECTOR)
	}
	
	/**
	 * MÉTODO SETGRADOS()
	 * @param hora - EQUIVALE A LA POSICIÓN DEL VALOR A DEVOLVER EN EL VECTOR.
	 * @return GRADOS EN LA POSICIÓN HORA DEL VECTOR
	 */
	public double getGrados(int hora) {		//DEVUELVE GRADOS
		return grados[hora];		//DEVOLVER LOS GRADOS EN LA POSICIÓN (HORA)
		//(VECTOR.[INT] - DEVUELVE EL VALOR EN POSICIÓN INT DEL VECTOR)
	}
	
	/**
	 * MÉTODO MEDIA()
	 * 	UTILIZARÁ UN BUCLE FOR QUE SE REPETIRÁ 24 VECES (UNA PARA CADA HORA)
	 * 	PODDRÍAMOS ESCRIBIR H<=24 COMO CONDICIÓN EN EL FOR. GRADOS.LENGTH HACE LA MISMA FUNCIÓN.
	 * 		(VECTOR.LENGTH DEVUELVE LA LONGITUD DE UN VECTOR, EN ESTE CASO, 24)
	 * 
	 * 	CADA VUELTA QUE DE, SUMARÁ EL VALOR DE LA TEMPERATURA A UN SUMATORIO EN LA VARIABLE SUMA.
	 * @return SUMA/24.0 - EQUIVALENTE A LA MEDIA DE TODAS LAS TEMPERATURAS DEL VECTOR
	 */
	public double media() {		//CALCULA MEDIA GRADOS
		double suma = 0;		//INICIALIZA SUMATORIO
		for (int h=0;h<grados.length;h++) {		//REPETIR TANTAS VECES COMO ELEMENTOS EN EL VECTOR
			suma = (double) suma + grados[h];		//CALCULAR SUMATORIO
		}
		return (double) (suma/24.0);		//DEVOLVER MEDIA
	}
	
	/**
	 * MÉTODO MAX()
	 * 	UTILIZARÁ UN BUCLE FOR QUE SE REPETIRÁ 24 VECES (UNA PARA CADA HORA)
	 * 		PODRÍAMOS UTILIZAR H<GRADOS.LENGTH COMO EN EL MÉTODO MEDIA()
	 * 
	 * CADA VUELTA QUE DE, COMPARARÁ LA TEMPERATURA MÁXIMA ALMACENADA EN MAX Y SI ES MAYOR, ACTUALIZARÁ MAX.
	 * @return MAYOR VALOR DE TODO EL VECTOR - EQUIVALENTE A LA TEMPERATURA MÁXIMA DEL DÍA.
	 */
	public double max() {		//CALCULA TEMPERATURA MÁXIMA (VALOR MÁXIMO DEL VECTOR)
		double max=grados[0];		//TEMPERATURA MÁXIMA
		for (int h=1;h<24;h++) {		//REPETIR 24 VECES
			if (grados[h]>max);		//SI ESTE VALOR DEL VECTOR ES MAYOR QUE EL MAYOR HASTA AHORA
			max=grados[h];		//ACTUALIZAR MAYOR
		}
		return max;		//DEVOLVER MAYOR
	}
	
	public void pintaGráfico() {
		for (int h=0;h<24;h++) {
			System.out.printf("%d : ",h);
				for (int i=1;i<=grados[h];i++) {
					System.out.print("*");
				System.out.println("");
				}
		}
	}
}